<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <OutputType>WinExe</OutputType>

    <!-- WinUI 3 -->
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>

    <!-- Project Options -->
    <RootNamespace>Pail.App</RootNamespace>
    <AssemblyName>Pail</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <!-- App Options -->
    <UseRidGraph>true</UseRidGraph>
    <Platforms>x86;x64;ARM64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Pail.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!--  App Version and Assembly Info  -->
    <Version>1.2.0.0</Version>
    <AssemblyTitle>Pail</AssemblyTitle>
    <AssemblyProduct>TheBlueSky.Pail</AssemblyProduct>
    <AssemblyCopyright>Copyright © TheBlueSky. All rights reserved.</AssemblyCopyright>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <AssemblyFileVersion>$(Version)</AssemblyFileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="WinUI.TableView" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pail.Core\Pail.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\*.png" />
    <Content Include="Assets\Pail.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
    Explorer "Package and Publish" context menu entry to be enabled for this project even if 
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <Target Name="DeletePublishPdbs" AfterTargets="Publish" Condition="'$(PublishSingleFile)'=='true' and '$(CopyOutputSymbolsToPublishDirectory)'=='false'">
    <ItemGroup>
      <PublishedSymbols Include="$(PublishDir)*.pdb" />
    </ItemGroup>

    <Delete Files="@(PublishedSymbols)" />
  </Target>

</Project>
